<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Happy_Reader_Tests</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyTitle>Happy Reader Tests</AssemblyTitle>
    <Product>Happy Reader Tests</Product>
    <Copyright>Copyright ©  2017</Copyright>
    <Platforms>x64;x86</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <None Include="IpaDic\AUTHORS" />
    <None Include="IpaDic\char.bin" />
    <None Include="IpaDic\COPYING" />
    <None Include="IpaDic\matrix.bin" />
    <None Include="IpaDic\sys.dic" />
    <None Include="IpaDic\unk.dic" />
    <PackageReference Include="Kawazu" Version="1.1.4" />
    <PackageReference Include="LibNMeCab" Version="0.10.2" />
    <PackageReference Include="LibNMeCab.IpaDicBin" Version="0.10.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Happy Reader\Happy Reader.csproj" />
    <ProjectReference Include="..\HappySearchObjectClasses\Happy_Apps_Core.csproj" />
  </ItemGroup>
</Project>