<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>HRGoogleTranslate</AssemblyTitle>
    <Description>Google Translate Plugin for Happy Reader</Description>
    <Product>HRGoogleTranslate</Product>
    <Platforms>x64;x86</Platforms>
    <Copyright>Copyright © Zoltanar 2017-2025</Copyright>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>..\Debug64\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>..\Release64\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>..\Debug\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>..\Release\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HappySearchObjectClasses\Happy_Apps_Core.csproj" />
    <PackageReference Include="Google.Api.Gax" Version="4.13.0" />
    <PackageReference Include="Google.Api.Gax.Rest" Version="4.13.0" />
    <PackageReference Include="Google.Apis" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Translate.v2" Version="1.68.0.875" />
    <PackageReference Include="Google.Cloud.Translation.V2" Version="3.5.0">
    </PackageReference>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>