//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy_Apps_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Happy_Apps_Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only consist of alphanumeric characters..
        /// </summary>
        internal static string _username_only_alphanumeric {
            get {
                return ResourceManager.GetString("_username_only_alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} (Version {1}, for VNDB API {2})\nBy Zoltanar (https://vndb.org/u47063/)\nBuilt from onkelsam&apos;s app \&quot;Visual Novel Database\&quot; https://vndb.org/t3599.48 \nwho used fredthebarber&apos;s app for handling connection and queries https://vndb.org/t3599.41&quot;.
        /// </summary>
        internal static string about_text {
            get {
                return ResourceManager.GetString("about_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged in..
        /// </summary>
        internal static string already_logged_in {
            get {
                return ResourceManager.GetString("already_logged_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to overwrite?.
        /// </summary>
        internal static string ask_overwrite {
            get {
                return ResourceManager.GetString("ask_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Action.
        /// </summary>
        internal static string Confirm_Action {
            get {
                return ResourceManager.GetString("Confirm_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to VNDB..
        /// </summary>
        internal static string connection_failed {
            get {
                return ResourceManager.GetString("connection_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeUserlistStatus Query Error.
        /// </summary>
        internal static string cus_query_error {
            get {
                return ResourceManager.GetString("cus_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeVote Query Error.
        /// </summary>
        internal static string cv_query_error {
            get {
                return ResourceManager.GetString("cv_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeVNStatus Query Error.
        /// </summary>
        internal static string cvns_query_error {
            get {
                return ResourceManager.GetString("cvns_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeWishlistStatus Query Error.
        /// </summary>
        internal static string cws_query_error {
            get {
                return ResourceManager.GetString("cws_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown DBS Error.
        /// </summary>
        internal static string dbs_unknown_error {
            get {
                return ResourceManager.GetString("dbs_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS Error while requesting information. Response: .
        /// </summary>
        internal static string dbstats_error {
            get {
                return ResourceManager.GetString("dbstats_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Producer Name..
        /// </summary>
        internal static string enter_producer_name {
            get {
                return ResourceManager.GetString("enter_producer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User ID.
        /// </summary>
        internal static string enter_user_id {
            get {
                return ResourceManager.GetString("enter_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username and Password.
        /// </summary>
        internal static string enter_username_password {
            get {
                return ResourceManager.GetString("enter_username_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter VN title.
        /// </summary>
        internal static string enter_vn_title {
            get {
                return ResourceManager.GetString("enter_vn_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter year..
        /// </summary>
        internal static string enter_year {
            get {
                return ResourceManager.GetString("enter_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Wrong password or possibly server error..
        /// </summary>
        internal static string error_wrong_password_or_server {
            get {
                return ResourceManager.GetString("error_wrong_password_or_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter cleared..
        /// </summary>
        internal static string filter_cleared {
            get {
                return ResourceManager.GetString("filter_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Deleted.
        /// </summary>
        internal static string filter_deleted {
            get {
                return ResourceManager.GetString("filter_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter saved..
        /// </summary>
        internal static string filter_saved {
            get {
                return ResourceManager.GetString("filter_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to do this?
        ///This may take a while if you have a lot of favorite producers....
        /// </summary>
        internal static string get_new_fp_titles_confirm {
            get {
                return ResourceManager.GetString("get_new_fp_titles_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got new titles from all favorite producers..
        /// </summary>
        internal static string get_new_fp_titles_success {
            get {
                return ResourceManager.GetString("get_new_fp_titles_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMultipleVN Query Error.
        /// </summary>
        internal static string gmvn_query_error {
            get {
                return ResourceManager.GetString("gmvn_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPTM Query Error.
        /// </summary>
        internal static string gptm_query_error {
            get {
                return ResourceManager.GetString("gptm_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSingleVN Query Error.
        /// </summary>
        internal static string gsvn_query_error {
            get {
                return ResourceManager.GetString("gsvn_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUserList Query Error.
        /// </summary>
        internal static string gul_query_error {
            get {
                return ResourceManager.GetString("gul_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got User Related Titles.
        /// </summary>
        internal static string gurt_success {
            get {
                return ResourceManager.GetString("gurt_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVoteList Query Error.
        /// </summary>
        internal static string gvl_query_error {
            get {
                return ResourceManager.GetString("gvl_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetWishList Query Error.
        /// </summary>
        internal static string gwl_query_error {
            get {
                return ResourceManager.GetString("gwl_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetYearTitles Query Error.
        /// </summary>
        internal static string gyt_query_error {
            get {
                return ResourceManager.GetString("gyt_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item changed..
        /// </summary>
        internal static string item_changed {
            get {
                return ResourceManager.GetString("item_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Log In.
        /// </summary>
        internal static string log_in_failure {
            get {
                return ResourceManager.GetString("log_in_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In.
        /// </summary>
        internal static string log_in_success {
            get {
                return ResourceManager.GetString("log_in_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Login Error.
        /// </summary>
        internal static string login_unknown_error {
            get {
                return ResourceManager.GetString("login_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be integer.
        /// </summary>
        internal static string must_be_integer {
            get {
                return ResourceManager.GetString("must_be_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items selected..
        /// </summary>
        internal static string no_items_selected {
            get {
                return ResourceManager.GetString("no_items_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No list found..
        /// </summary>
        internal static string no_list_found {
            get {
                return ResourceManager.GetString("no_list_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results..
        /// </summary>
        internal static string no_results {
            get {
                return ResourceManager.GetString("no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS Query Error.
        /// </summary>
        internal static string ps_query_error {
            get {
                return ResourceManager.GetString("ps_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Error.
        /// </summary>
        internal static string query_error {
            get {
                return ResourceManager.GetString("query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set your UserID first..
        /// </summary>
        internal static string set_userid_first {
            get {
                return ResourceManager.GetString("set_userid_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP Query Error.
        /// </summary>
        internal static string sp_query_error {
            get {
                return ResourceManager.GetString("sp_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single VN Query Error.
        /// </summary>
        internal static string svn_query_error {
            get {
                return ResourceManager.GetString("svn_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULR Query Error.
        /// </summary>
        internal static string ulr_query_error {
            get {
                return ResourceManager.GetString("ulr_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may take a while depending on how many titles will be found.
        ///Are you sure?.
        /// </summary>
        internal static string update_custom_filter {
            get {
                return ResourceManager.GetString("update_custom_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated all favorite producer titles..
        /// </summary>
        internal static string update_fp_titles_success {
            get {
                return ResourceManager.GetString("update_fp_titles_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Updating URT.
        /// </summary>
        internal static string updated_urt {
            get {
                return ResourceManager.GetString("updated_urt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPT Query Error.
        /// </summary>
        internal static string upt_query_error {
            get {
                return ResourceManager.GetString("upt_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPTR Query Error.
        /// </summary>
        internal static string uptr_query_error {
            get {
                return ResourceManager.GetString("uptr_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID must contain only numbers.
        /// </summary>
        internal static string userid_only_numbers {
            get {
                return ResourceManager.GetString("userid_only_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateSingleVN Query Error.
        /// </summary>
        internal static string usvn_query_error {
            get {
                return ResourceManager.GetString("usvn_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid votes are between 1 and 10..
        /// </summary>
        internal static string valid_vote_error {
            get {
                return ResourceManager.GetString("valid_vote_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Novel Information.
        /// </summary>
        internal static string visual_novel_information {
            get {
                return ResourceManager.GetString("visual_novel_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VN Query Error.
        /// </summary>
        internal static string vn_query_error {
            get {
                return ResourceManager.GetString("vn_query_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated just now..
        /// </summary>
        internal static string vn_updated {
            get {
                return ResourceManager.GetString("vn_updated", resourceCulture);
            }
        }
    }
}
