<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>HRDeepLTranslate</AssemblyTitle>
    <Description>DeepL Plugin for Happy Reader</Description>
    <Product>HRDeepLTranslate</Product>
	  <Platforms>x64;x86</Platforms>
    <Copyright>Copyright © Zoltanar 2026</Copyright>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
		<OutputPath>..\Debug64\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
		<OutputPath>..\Release64\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
		<OutputPath>..\Debug\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
		<OutputPath>..\Release\net10.0-windows\Program Data\Translation Plugins\</OutputPath>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HappySearchObjectClasses\Happy_Apps_Core.csproj" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>